name: Build and Push to ACR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Image
      run: |
        az acr login --name gondiacr
        docker build -t gondiacr.azurecr.io/myapp:v1 .
        docker push gondiacr.azurecr.io/myapp:v1
